# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_kreyren D0501F7980EA70D192C03A52667F0DAFAF09BA2B
  - &system_pelagus 2f9777289377e1ec1feda2b1a6faab3bf05193dd
creation_rules:
  # - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
  #   key_groups:
  #   - pgp:
  #     - *admin_kreyren
  #     # - *system_pelagus

  # Kreyren Password
  - path_regex: users/kreyren/kreyren-user-password\.yaml$
    key_groups:
    - pgp:
      - *admin_kreyren
      # - *system_pelagus
